
FROM java:8
ADD ./target/helloworld-0.0.1-SNAPSHOT helloworld.jar
ECHO ">>>>>> JAR Added Successfully"
EXPOSE 9000
ENTRYPOINT ["java","-jar","helloworld.jar"]
ECHO ">>>>>> Docker Image Build Successfully"